package interfaces;

import conecxiones.conectar;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;

public class productos extends javax.swing.JFrame {

    private double sumaGlobal = 0.0;
    conectar con;

    public productos() {
        initComponents();
        mostrarIva();
        mostrarProductos();
        cargarIvaEnCombo();
        mostrarDepartamento();
        cargarCategoriasEnCombo();
        sminimo.setVisible(false);
        smaximo.setVisible(false);
        cantidad.setVisible(false);
        cantidadt.setVisible(false);
        sminimot.setVisible(false);
        smaximot.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ventas = new javax.swing.JButton();
        credito = new javax.swing.JButton();
        clientes = new javax.swing.JButton();
        compras = new javax.swing.JButton();
        productos = new javax.swing.JButton();
        inventario = new javax.swing.JButton();
        factura = new javax.swing.JButton();
        configuracion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ivas = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        barras = new javax.swing.JTextField();
        subir = new javax.swing.JButton();
        descripcion = new javax.swing.JTextField();
        unidad = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ganancia = new javax.swing.JTextField();
        precioVenta = new javax.swing.JTextField();
        precioCompra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        mayoreo = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        smaximot = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        sminimo = new javax.swing.JTextField();
        sminimot = new javax.swing.JLabel();
        cantidadt = new javax.swing.JLabel();
        smaximo = new javax.swing.JTextField();
        tiva = new javax.swing.JLabel();
        ivacombox = new javax.swing.JComboBox();
        departamentocombox = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaModificar = new javax.swing.JTable();
        borrarModificar = new javax.swing.JButton();
        GuardarModificar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtPorcentajeIva = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        subiriva = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaiva = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        departamentoe = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaDepartamento = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        guardarDepartamento = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ventas.setText("Ventas");
        ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasActionPerformed(evt);
            }
        });

        credito.setText("Creditos");
        credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditoActionPerformed(evt);
            }
        });

        clientes.setText("clientes");
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });

        compras.setText("Compras");

        productos.setText("Productos");
        productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosActionPerformed(evt);
            }
        });

        inventario.setText("Inventario");
        inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioActionPerformed(evt);
            }
        });

        factura.setText("Factura");

        configuracion.setText("Configuracion");

        barras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barrasActionPerformed(evt);
            }
        });

        subir.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        subir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/subir.png"))); // NOI18N
        subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirActionPerformed(evt);
            }
        });

        descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionActionPerformed(evt);
            }
        });

        unidad.setText("unidad");

        jLabel2.setText("se vende");

        jRadioButton1.setText("granel");

        jRadioButton2.setText("paquete");

        jLabel3.setText("codigo de barras");

        jLabel4.setText("Descipcion");

        jLabel5.setText("Precio de venta");

        jLabel9.setText("Precio de compra");

        jLabel10.setText("Ganancia");

        ganancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gananciaActionPerformed(evt);
            }
        });

        precioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioVentaActionPerformed(evt);
            }
        });

        precioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioCompraActionPerformed(evt);
            }
        });

        jLabel11.setText("Venta mayoreo");

        jLabel12.setText("Departamento");

        mayoreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayoreoActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Inventariado");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        smaximot.setText("Stock maximo");

        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });

        sminimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sminimoActionPerformed(evt);
            }
        });

        sminimot.setText("Strock minimo");

        cantidadt.setText("Cantidad");

        smaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smaximoActionPerformed(evt);
            }
        });

        tiva.setText("Iva  ");

        ivacombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ivacomboxActionPerformed(evt);
            }
        });

        departamentocombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentocomboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(unidad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(58, 58, 58)
                            .addComponent(barras, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jRadioButton3)
                        .addGap(182, 182, 182)
                        .addComponent(tiva)
                        .addGap(18, 18, 18)
                        .addComponent(ivacombox, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sminimot)
                                    .addComponent(smaximot)
                                    .addComponent(cantidadt))
                                .addGap(44, 44, 44)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(precioVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(ganancia, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(precioCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(mayoreo)
                            .addComponent(cantidad)
                            .addComponent(sminimo)
                            .addComponent(smaximo)
                            .addComponent(departamentocombox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addComponent(subir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(651, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barras, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unidad)
                            .addComponent(jLabel2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(precioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(precioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tiva)
                                    .addComponent(ivacombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ganancia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(mayoreo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(departamentocombox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton3)
                        .addGap(18, 18, 18)
                        .addComponent(cantidadt))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sminimo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sminimot))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(smaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(smaximot)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(subir)))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        ivas.addTab("Nuevo", jPanel2);

        tablaModificar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaModificar);

        borrarModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        borrarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarModificarActionPerformed(evt);
            }
        });

        GuardarModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        GuardarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarModificarActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel14.setText("Modifica Productos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addComponent(GuardarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(borrarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GuardarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarModificar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        ivas.addTab("Modificar", jPanel3);

        txtPorcentajeIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorcentajeIvaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel13.setText("iva");

        subiriva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/subir.png"))); // NOI18N
        subiriva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirivaActionPerformed(evt);
            }
        });

        tablaiva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaiva);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel15.setText("Edita IVA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txtPorcentajeIva, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(subiriva, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel15)))
                .addContainerGap(710, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPorcentajeIva, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addComponent(subiriva, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        ivas.addTab("Iva", jPanel4);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Nombre departamento");

        departamentoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentoeActionPerformed(evt);
            }
        });

        tablaDepartamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaDepartamento);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Editar departemento");

        guardarDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/subir.png"))); // NOI18N
        guardarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDepartamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(departamentoe, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(guardarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel7)))))
                .addContainerGap(627, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(departamentoe, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guardarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        ivas.addTab("Departamento", jPanel1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1297, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        ivas.addTab("paquetes", jPanel5);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Panel de Administrador ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(credito, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(compras, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(factura, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(ivas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(credito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(compras, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(factura, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ivas, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasActionPerformed
        // Button 1:
    }//GEN-LAST:event_ventasActionPerformed

    private void creditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditoActionPerformed
        // Button 2 :
    }//GEN-LAST:event_creditoActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        // Button 3
    }//GEN-LAST:event_clientesActionPerformed

    private void productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productosActionPerformed

    private void inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventarioActionPerformed

    private void barrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barrasActionPerformed

    private void descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionActionPerformed

    }//GEN-LAST:event_descripcionActionPerformed

    private void gananciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gananciaActionPerformed
        KeyAdapter keyAdapter = new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                calcularGanancia();
            }
        };

        precioCompra.addKeyListener(keyAdapter);
        precioVenta.addKeyListener(keyAdapter);
    }//GEN-LAST:event_gananciaActionPerformed
    private void agregarDocumentListenerParaGanancia() {
        DocumentListener docListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                calcularGanancia();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                calcularGanancia();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                calcularGanancia();
            }
        };

        precioCompra.getDocument().addDocumentListener(docListener);
        precioVenta.getDocument().addDocumentListener(docListener);
    }

// Método que calcula la ganancia
    private void calcularGanancia() {
        try {
            double venta = Double.parseDouble(precioVenta.getText());
            double compra = Double.parseDouble(precioCompra.getText());

            double resultado = venta - compra;
            sumaGlobal = resultado;

            // Mostrar con 2 decimales
            ganancia.setText(String.format("%.2f", resultado));
            // Cambiar color según si es negativa
            if (resultado < 0) {
                ganancia.setForeground(Color.RED);
            } else {
                ganancia.setForeground(Color.BLACK);
            }

        } catch (NumberFormatException e) {
            ganancia.setText("0.00"); // Valor por defecto si no hay números
            ganancia.setForeground(Color.BLACK);
        }
    }
    private void precioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioVentaActionPerformed
        // Solo validar el contenido actual
        String texto = precioVenta.getText();

        try {
            // Intentamos convertir a número (aceptando decimales)
            double valor = Double.parseDouble(texto);
            // Si es válido, dejamos el texto tal cual
            precioVenta.setText(String.valueOf(valor));
        } catch (NumberFormatException e) {
            // Si no es válido, borramos o mostramos error
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Solo se permiten números", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            precioVenta.setText("");
        }
    }//GEN-LAST:event_precioVentaActionPerformed

    private void precioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioCompraActionPerformed

        String texto = precioCompra.getText();

        try {
            // Intentamos convertir a número (aceptando decimales)
            double valor = Double.parseDouble(texto);
            // Si es válido, dejamos el texto tal cual
            precioCompra.setText(String.valueOf(valor));
        } catch (NumberFormatException e) {
            // Si no es válido, borramos o mostramos error
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Solo se permiten números", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            precioCompra.setText("");
        }
    }//GEN-LAST:event_precioCompraActionPerformed

    private void mayoreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayoreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mayoreoActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // Cantidad
    }//GEN-LAST:event_cantidadActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // Boton 
        // Si el botón está seleccionado, mostrar los campos
        if (jRadioButton3.isSelected()) {
            sminimo.setVisible(true);
            smaximo.setVisible(true);
            cantidad.setVisible(true);
            cantidadt.setVisible(true);
            sminimot.setVisible(true);
            smaximot.setVisible(true);
        } else {
            // Si se deselecciona, ocultarlos
            sminimo.setVisible(false);
            smaximo.setVisible(false);
            cantidad.setVisible(false);
            cantidadt.setVisible(false);
            sminimot.setVisible(false);
            smaximot.setVisible(false);
        }

        // Refrescar el panel para aplicar los cambios visuales
        jPanel2.revalidate();
        jPanel2.repaint();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void sminimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sminimoActionPerformed
        //Sminimo
    }//GEN-LAST:event_sminimoActionPerformed

    private void smaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smaximoActionPerformed
        //Smaximo
    }//GEN-LAST:event_smaximoActionPerformed

    private void subirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirActionPerformed
        //Subir
        conectar con = new conectar();
        Connection cn = null;
        PreparedStatement psProducto = null;
        PreparedStatement psInventario = null;
        ResultSet rs = null;

        try {
            cn = con.getConnection();

            // --- Tipo de venta ---
            String tipoVenta = "unidad";
            if (jRadioButton1.isSelected()) {
                tipoVenta = "granel";
            } else if (jRadioButton2.isSelected()) {
                tipoVenta = "paquete";
            }

            boolean inventariado = jRadioButton3.isSelected();

            // --- Obtener el IVA seleccionado ---
            ComboItem itemIva = (ComboItem) ivacombox.getSelectedItem();
            int idIvaSeleccionado = itemIva != null ? itemIva.getId() : 1;

            // --- Obtener la categoría seleccionada ---
            ComboItem itemCategoria = (ComboItem) departamentocombox.getSelectedItem();
            int idCategoriaSeleccionada = itemCategoria != null ? itemCategoria.getId() : 1;

            // --- Insertar producto con IVA y categoría ---
            String sqlProducto = "INSERT INTO productos (codigo_barras, descripcion, precio_compra, precio_venta, ganancia, venta_mayoreo, inventariado, tipo_venta, id_iva, id_categoria) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

            psProducto = cn.prepareStatement(sqlProducto, Statement.RETURN_GENERATED_KEYS);
            psProducto.setString(1, barras.getText());
            psProducto.setString(2, descripcion.getText());
            psProducto.setDouble(3, Double.parseDouble(precioCompra.getText()));
            psProducto.setDouble(4, Double.parseDouble(precioVenta.getText()));
            psProducto.setDouble(5, Double.parseDouble(ganancia.getText()));
            psProducto.setDouble(6, Double.parseDouble(mayoreo.getText()));
            psProducto.setBoolean(7, inventariado);
            psProducto.setString(8, tipoVenta);
            psProducto.setInt(9, idIvaSeleccionado);
            psProducto.setInt(10, idCategoriaSeleccionada);

            int filas = psProducto.executeUpdate();

            if (filas > 0) {
                rs = psProducto.getGeneratedKeys();
                if (rs.next()) {
                    int idProducto = rs.getInt(1);

                    // --- Agregar inventario si aplica ---
                    if (inventariado) {
                        String sqlInventario = "INSERT INTO inventario (id_producto, cantidad, stock_minimo, stock_maximo) VALUES (?, ?, ?, ?)";
                        psInventario = cn.prepareStatement(sqlInventario);
                        psInventario.setInt(1, idProducto);
                        psInventario.setInt(2, Integer.parseInt(cantidad.getText()));
                        psInventario.setInt(3, Integer.parseInt(sminimo.getText()));
                        psInventario.setInt(4, Integer.parseInt(smaximo.getText()));
                        psInventario.executeUpdate();
                    }

                    JOptionPane.showMessageDialog(this, "✅ Producto agregado con IVA y departamento.");
                    mostrarProductos();
                }
            } else {
                JOptionPane.showMessageDialog(this, "❌ Error al agregar el producto.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "⚠️ Error: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (psProducto != null) {
                    psProducto.close();
                }
                if (psInventario != null) {
                    psInventario.close();
                }
                if (cn != null) {
                    cn.close();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_subirActionPerformed
    public class ComboItem {

        private int id;
        private String texto;

        public ComboItem(int id, String texto) {
            this.id = id;
            this.texto = texto;
        }

        public int getId() {
            return id;
        }

        @Override
        public String toString() {
            return texto; // Lo que se muestra en el combo
        }
    }

    private void txtPorcentajeIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorcentajeIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorcentajeIvaActionPerformed

    private void subirivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirivaActionPerformed

        String porcentajeTexto = txtPorcentajeIva.getText().trim();

// Validar que el porcentaje sea un número
        if (!porcentajeTexto.matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, "Ingresa un valor correcto en porcentaje.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Connection cn = null;
        PreparedStatement psIva = null;
        ResultSet rs = null;

        try {
            // Crear instancia de la clase conectar
            con = new conectar();
            cn = con.getConnection(); // Obtener conexión

            // SQL de inserción solo con porcentaje
            String sqlIva = "INSERT INTO iva (porcentaje) VALUES (?)";
            psIva = cn.prepareStatement(sqlIva, Statement.RETURN_GENERATED_KEYS);
            psIva.setDouble(1, Double.parseDouble(porcentajeTexto)); // Índice 1 porque solo hay un ?

            int filas = psIva.executeUpdate();

            if (filas > 0) {
                rs = psIva.getGeneratedKeys();
                if (rs.next()) {
                    int idIva = rs.getInt(1);
                    JOptionPane.showMessageDialog(this, "✅ IVA agregado correctamente. ID: " + idIva);
                    mostrarIva();
                    mostrarProductos();
                    cargarIvaEnCombo();
                }
            } else {
                JOptionPane.showMessageDialog(this, "❌ Error al agregar el IVA.");
            }

            // Limpiar campo
            txtPorcentajeIva.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "⚠️ Error: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (psIva != null) {
                    psIva.close();
                }
                if (cn != null) {
                    cn.close(); // Cerramos la conexión después del insert
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_subirivaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaiva.getSelectedRow();

        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un registro para eliminar.");
            return;
        }

        // Obtener el ID del IVA desde la tabla
        int idIva = Integer.parseInt(tablaiva.getValueAt(filaSeleccionada, 0).toString());

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que deseas eliminar el IVA con ID: " + idIva + "?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            conecxiones.conectar con = new conecxiones.conectar();
            java.sql.Connection cn = con.getConnection();
            java.sql.PreparedStatement ps = null;

            try {
                String sql = "DELETE FROM iva WHERE id_iva = ?";
                ps = cn.prepareStatement(sql);
                ps.setInt(1, idIva);
                int filasAfectadas = ps.executeUpdate();

                if (filasAfectadas > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "IVA eliminado correctamente.");
                    mostrarIva(); // 🔄 Actualiza la tabla
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "No se encontró el registro a eliminar.");
                }

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar IVA: " + e.getMessage());
                e.printStackTrace();
            } finally {
                try {
                    if (ps != null) {
                        ps.close();
                    }
                    con.desconectar();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        conecxiones.conectar con = new conecxiones.conectar();
        java.sql.Connection cn = con.getConnection();
        java.sql.PreparedStatement ps = null;

        try {
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaiva.getModel();

            int filas = modelo.getRowCount();
            int actualizados = 0;

            for (int i = 0; i < filas; i++) {
                int idIva = Integer.parseInt(modelo.getValueAt(i, 0).toString());
                double porcentaje = Double.parseDouble(modelo.getValueAt(i, 1).toString());

                String sql = "UPDATE iva SET porcentaje = ? WHERE id_iva = ?";
                ps = cn.prepareStatement(sql);
                ps.setDouble(1, porcentaje);
                ps.setInt(2, idIva);
                int resultado = ps.executeUpdate();

                if (resultado > 0) {
                    actualizados++;
                }
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Cambios guardados correctamente (" + actualizados + " registros actualizados).");

            // Refrescar la tabla para mostrar los valores actualizados
            mostrarIva();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar cambios: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (ps != null) {
                    ps.close();
                }
                con.desconectar();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ivacomboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ivacomboxActionPerformed


    }//GEN-LAST:event_ivacomboxActionPerformed

    private void GuardarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarModificarActionPerformed
        conecxiones.conectar con = new conecxiones.conectar();
        java.sql.Connection cn = con.getConnection();
        java.sql.PreparedStatement ps = null;

        try {
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaModificar.getModel();
            int filas = modelo.getRowCount();
            int actualizados = 0;

            for (int i = 0; i < filas; i++) {
                int idProducto = Integer.parseInt(modelo.getValueAt(i, 0).toString());
                String descripcion = modelo.getValueAt(i, 2).toString();
                double precioCompra = Double.parseDouble(modelo.getValueAt(i, 3).toString());
                double precioVenta = Double.parseDouble(modelo.getValueAt(i, 4).toString());
                double ganancia = Double.parseDouble(modelo.getValueAt(i, 5).toString());
                String nombreCategoria = modelo.getValueAt(i, 6).toString();
                double ventaMayoreo = Double.parseDouble(modelo.getValueAt(i, 7).toString());
                boolean inventariado = Boolean.parseBoolean(modelo.getValueAt(i, 8).toString());
                double iva = Double.parseDouble(modelo.getValueAt(i, 9).toString());
                String tipoVenta = modelo.getValueAt(i, 10).toString();

                // Obtener id_categoria e id_iva según el nombre/porcentaje
                int idCategoria = obtenerIdCategoria(nombreCategoria, cn);
                int idIva = obtenerIdIva(iva, cn);

                String sql = "UPDATE productos SET descripcion=?, precio_compra=?, precio_venta=?, ganancia=?, "
                        + "id_categoria=?, venta_mayoreo=?, inventariado=?, id_iva=?, tipo_venta=? WHERE id_producto=?";
                ps = cn.prepareStatement(sql);
                ps.setString(1, descripcion);
                ps.setDouble(2, precioCompra);
                ps.setDouble(3, precioVenta);
                ps.setDouble(4, ganancia);
                ps.setInt(5, idCategoria);
                ps.setDouble(6, ventaMayoreo);
                ps.setBoolean(7, inventariado);
                ps.setInt(8, idIva);
                ps.setString(9, tipoVenta);
                ps.setInt(10, idProducto);

                if (ps.executeUpdate() > 0) {
                    actualizados++;
                }
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Se actualizaron " + actualizados + " productos correctamente.");
            mostrarProductos();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar cambios: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (ps != null) {
                    ps.close();
                }
                con.desconectar();
            } catch (Exception e) {
            }
        }
    }

    private int obtenerIdCategoria(String nombreCategoria, java.sql.Connection cn) throws Exception {
        String sql = "SELECT id_categoria FROM categorias WHERE nombre_categoria = ?";
        java.sql.PreparedStatement ps = cn.prepareStatement(sql);
        ps.setString(1, nombreCategoria);
        java.sql.ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            return rs.getInt("id_categoria");
        }
        return 0;
    }

    private int obtenerIdIva(double porcentaje, java.sql.Connection cn) throws Exception {
        String sql = "SELECT id_iva FROM iva WHERE porcentaje = ?";
        java.sql.PreparedStatement ps = cn.prepareStatement(sql);
        ps.setDouble(1, porcentaje);
        java.sql.ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            return rs.getInt("id_iva");
        }
        return 0;
    }//GEN-LAST:event_GuardarModificarActionPerformed

    private void guardarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDepartamentoActionPerformed
        String nombreDepartamento = departamentoe.getText().trim(); // Obtener texto del campo

        if (nombreDepartamento.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar un nombre de departamento");
            return;
        }

        conecxiones.conectar con = new conecxiones.conectar();
        java.sql.Connection cn = con.getConnection();
        java.sql.PreparedStatement ps = null;

        try {
            String sql = "INSERT INTO categorias (nombre_categoria) VALUES (?)";
            ps = cn.prepareStatement(sql);
            ps.setString(1, nombreDepartamento);

            int resultado = ps.executeUpdate();
            if (resultado > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Departamento guardado correctamente");
                departamentoe.setText(""); // Limpiar campo
                mostrarDepartamento();
                mostrarProductos();// Refrescar la tabla
                cargarCategoriasEnCombo();
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar departamento: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (ps != null) {
                    ps.close();
                }
                con.desconectar();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_guardarDepartamentoActionPerformed
    private void mostrarDepartamento() {
        String[] columnas = {"ID", "Nombre del Departamento"};
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(null, columnas) {
            boolean[] canEdit = new boolean[]{false, true}; // editable solo el nombre

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        conecxiones.conectar con = new conecxiones.conectar();
        java.sql.Connection cn = con.getConnection();

        try {
            String sql = "SELECT id_categoria, nombre_categoria FROM categorias";
            java.sql.Statement st = cn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id_categoria"),
                    rs.getString("nombre_categoria")
                };
                modelo.addRow(fila);
            }

            tablaDepartamento.setModel(modelo);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al mostrar departamentos: " + e.getMessage());
            e.printStackTrace();
        } finally {
            con.desconectar();
        }
    }

    private void departamentoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentoeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departamentoeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Terminar cualquier edición activa en la tabla
        if (tablaDepartamento.isEditing()) {
            tablaDepartamento.getCellEditor().stopCellEditing();
        }

        conecxiones.conectar con = new conecxiones.conectar();
        java.sql.Connection cn = con.getConnection();
        java.sql.PreparedStatement ps = null;

        try {
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaDepartamento.getModel();
            int filas = modelo.getRowCount();
            int actualizados = 0;

            for (int i = 0; i < filas; i++) {
                int idCategoria = Integer.parseInt(modelo.getValueAt(i, 0).toString());
                String nombreCategoria = modelo.getValueAt(i, 1).toString().trim();

                // Validar que no esté vacío
                if (nombreCategoria.isEmpty()) {
                    continue;
                }

                String sql = "UPDATE categorias SET nombre_categoria = ? WHERE id_categoria = ?";
                ps = cn.prepareStatement(sql);
                ps.setString(1, nombreCategoria);
                ps.setInt(2, idCategoria);

                int resultado = ps.executeUpdate();
                if (resultado > 0) {
                    actualizados++;
                }
            }

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Cambios guardados correctamente (" + actualizados + " registros actualizados).");
            mostrarDepartamento(); // refrescar tabla

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar cambios: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (ps != null) {
                    ps.close();
                }
                con.desconectar();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int filaSeleccionada = tablaDepartamento.getSelectedRow();

        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un departamento para eliminar");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar este departamento?", "Confirmar eliminación", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        int idCategoria = Integer.parseInt(tablaDepartamento.getValueAt(filaSeleccionada, 0).toString());

        conecxiones.conectar con = new conecxiones.conectar();
        java.sql.Connection cn = con.getConnection();
        java.sql.PreparedStatement ps = null;

        try {
            String sql = "DELETE FROM categorias WHERE id_categoria = ?";
            ps = cn.prepareStatement(sql);
            ps.setInt(1, idCategoria);

            int resultado = ps.executeUpdate();
            if (resultado > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Departamento eliminado correctamente");
                mostrarDepartamento(); // refrescar tabla
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar departamento: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (ps != null) {
                    ps.close();
                }
                con.desconectar();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void departamentocomboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentocomboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departamentocomboxActionPerformed

    private void borrarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarModificarActionPerformed
        // Verificar si hay una fila seleccionada
        int filaSeleccionada = tablaModificar.getSelectedRow();
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un producto para eliminar.");
            return;
        }

        // Confirmar acción
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de eliminar este producto?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return; // Si el usuario elige "No", no hace nada
        }

        // Obtener el ID del producto de la fila seleccionada
        int idProducto = Integer.parseInt(tablaModificar.getValueAt(filaSeleccionada, 0).toString());

        // Conexión a la base de datos
        conecxiones.conectar con = new conecxiones.conectar();
        java.sql.Connection cn = con.getConnection();
        java.sql.PreparedStatement psInventario = null;
        java.sql.PreparedStatement psProducto = null;

        try {
            // 🔹 1. Eliminar el producto del inventario (si existe)
            String sqlInventario = "DELETE FROM inventario WHERE id_producto = ?";
            psInventario = cn.prepareStatement(sqlInventario);
            psInventario.setInt(1, idProducto);
            psInventario.executeUpdate();

            // 🔹 2. Eliminar el producto de la tabla productos
            String sqlProducto = "DELETE FROM productos WHERE id_producto = ?";
            psProducto = cn.prepareStatement(sqlProducto);
            psProducto.setInt(1, idProducto);
            int resultado = psProducto.executeUpdate();

            if (resultado > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Producto eliminado correctamente.");
                mostrarProductos(); // Actualizar tabla después de eliminar
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo eliminar el producto (no encontrado).");
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar producto: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (psInventario != null) {
                    psInventario.close();
                }
                if (psProducto != null) {
                    psProducto.close();
                }
                con.desconectar();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_borrarModificarActionPerformed
    private void cargarCategoriasEnCombo() {
        departamentocombox.removeAllItems();
        conecxiones.conectar con = new conecxiones.conectar();
        java.sql.Connection cn = con.getConnection();
        java.sql.PreparedStatement ps = null;
        java.sql.ResultSet rs = null;

        try {
            String sql = "SELECT id_categoria, nombre_categoria FROM categorias";
            ps = cn.prepareStatement(sql);
            rs = ps.executeQuery();

            while (rs.next()) {
                // Usa ComboItem para mostrar el nombre pero guardar el id
                departamentocombox.addItem(new ComboItem(rs.getInt("id_categoria"), rs.getString("nombre_categoria")));
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar categorías: " + e.getMessage());
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
                cn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void mostrarProductos() {
        // Definir columnas
        String[] columnas = {
            "ID", "Código de Barras", "Descripción", "Precio Compra",
            "Precio Venta", "Ganancia", "Categoría", "Venta Mayoreo",
            "Inventariado", "IVA (%)", "Tipo de Venta"
        };

        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(null, columnas) {
            boolean[] canEdit = new boolean[]{
                false, false, true, true,
                true, true, true, true,
                true, true, true
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        conecxiones.conectar con = new conecxiones.conectar();
        java.sql.Connection cn = con.getConnection();

        try {
            // Traer nombre_categoria, porcentaje IVA y tipo_venta descriptivo
            String sql = "SELECT p.id_producto, p.codigo_barras, p.descripcion, p.precio_compra, "
                    + "p.precio_venta, p.ganancia, c.nombre_categoria, p.venta_mayoreo, p.inventariado, "
                    + "i.porcentaje AS iva, p.tipo_venta "
                    + "FROM productos p "
                    + "LEFT JOIN categorias c ON p.id_categoria = c.id_categoria "
                    + "LEFT JOIN iva i ON p.id_iva = i.id_iva";

            java.sql.Statement st = cn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id_producto"),
                    rs.getString("codigo_barras"),
                    rs.getString("descripcion"),
                    rs.getDouble("precio_compra"),
                    rs.getDouble("precio_venta"),
                    rs.getDouble("ganancia"),
                    rs.getString("nombre_categoria"), // ahora muestra el nombre
                    rs.getDouble("venta_mayoreo"),
                    rs.getBoolean("inventariado"),
                    rs.getDouble("iva"), // porcentaje IVA
                    rs.getString("tipo_venta") // texto descriptivo (unidad, granel, paquete)
                };
                modelo.addRow(fila);
            }

            tablaModificar.setModel(modelo);

            // --- Agregar combos de selección en las columnas ---
            // Categoría
            javax.swing.JComboBox<String> comboCategoria = new javax.swing.JComboBox<>();
            cargarCategorias(comboCategoria);
            javax.swing.DefaultCellEditor editorCategoria = new javax.swing.DefaultCellEditor(comboCategoria);
            tablaModificar.getColumnModel().getColumn(6).setCellEditor(editorCategoria);

            // IVA
            javax.swing.JComboBox<String> comboIVA = new javax.swing.JComboBox<>();
            cargarIva(comboIVA);
            javax.swing.DefaultCellEditor editorIVA = new javax.swing.DefaultCellEditor(comboIVA);
            tablaModificar.getColumnModel().getColumn(9).setCellEditor(editorIVA);

            // Tipo de venta
            javax.swing.JComboBox<String> comboTipoVenta = new javax.swing.JComboBox<>();
            comboTipoVenta.addItem("unidad");
            comboTipoVenta.addItem("granel");
            comboTipoVenta.addItem("paquete");
            javax.swing.DefaultCellEditor editorTipoVenta = new javax.swing.DefaultCellEditor(comboTipoVenta);
            tablaModificar.getColumnModel().getColumn(10).setCellEditor(editorTipoVenta);
            // 🔄 NUEVO: Combo para Inventariado (true / false)
            javax.swing.JComboBox<String> comboInventariado = new javax.swing.JComboBox<>();
            comboInventariado.addItem("true");
            comboInventariado.addItem("false");
            javax.swing.DefaultCellEditor editorInventariado = new javax.swing.DefaultCellEditor(comboInventariado);
            tablaModificar.getColumnModel().getColumn(8).setCellEditor(editorInventariado);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al mostrar productos: " + e.getMessage());
            e.printStackTrace();
        } finally {
            con.desconectar();
        }
    }

// --- Métodos auxiliares ---
    private void cargarCategorias(javax.swing.JComboBox<String> combo) {
        combo.removeAllItems();
        conecxiones.conectar con = new conecxiones.conectar();
        java.sql.Connection cn = con.getConnection();
        try {
            java.sql.Statement st = cn.createStatement();
            java.sql.ResultSet rs = st.executeQuery("SELECT nombre_categoria FROM categorias");
            while (rs.next()) {
                combo.addItem(rs.getString("nombre_categoria"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            con.desconectar();
        }
    }

    private void cargarIva(javax.swing.JComboBox<String> combo) {
        combo.removeAllItems();
        conecxiones.conectar con = new conecxiones.conectar();
        java.sql.Connection cn = con.getConnection();
        try {
            java.sql.Statement st = cn.createStatement();
            java.sql.ResultSet rs = st.executeQuery("SELECT porcentaje FROM iva");
            while (rs.next()) {
                combo.addItem(rs.getString("porcentaje"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            con.desconectar();
        }
    }

    private void cargarIvaEnCombo() {
        conecxiones.conectar con = new conecxiones.conectar();
        java.sql.Connection cn = con.getConnection();
        java.sql.PreparedStatement ps = null;
        java.sql.ResultSet rs = null;

        try {
            ivacombox.removeAllItems(); // limpiar combo antes de cargar

            String sql = "SELECT id_iva, porcentaje FROM iva";
            ps = cn.prepareStatement(sql);
            rs = ps.executeQuery();

            boolean hay = false;
            java.text.DecimalFormat df = new java.text.DecimalFormat("0.00");

            while (rs.next()) {
                hay = true;
                int id = rs.getInt("id_iva");
                double porcentaje = rs.getDouble("porcentaje");
                String texto = df.format(porcentaje) + " %";

                ivacombox.addItem(new ComboItem(id, texto));
            }

            if (!hay) {
                JOptionPane.showMessageDialog(this, "No hay registros de IVA en la base de datos.", "Sin datos", JOptionPane.WARNING_MESSAGE);
            } else if (ivacombox.getItemCount() > 0) {
                ivacombox.setSelectedIndex(0); // seleccionamos el primero
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar IVAs: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (ps != null) {
                    ps.close();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            con.desconectar();
        }
    }

    private void mostrarIva() {
        // Definir columnas
        String[] columnas = {"ID", "Porcentaje"};
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(null, columnas) {
            boolean[] canEdit = new boolean[]{false, true}; // Solo editable el porcentaje

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        // Crear instancia de la conexión
        con = new conecxiones.conectar();
        java.sql.Connection cn = con.getConnection();

        try {
            String sql = "SELECT id_iva, porcentaje FROM iva";
            java.sql.Statement st = cn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            // Agregar filas al modelo
            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id_iva"),
                    rs.getDouble("porcentaje")
                };
                modelo.addRow(fila);
            }

            // Asignar modelo a la JTable
            tablaiva.setModel(modelo);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al mostrar IVA: " + e.getMessage());
            e.printStackTrace();
        } finally {
            // Cerrar la conexión
            con.desconectar();
        }
    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productos().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarModificar;
    private javax.swing.JTextField barras;
    private javax.swing.JButton borrarModificar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JLabel cantidadt;
    private javax.swing.JButton clientes;
    private javax.swing.JButton compras;
    private javax.swing.JButton configuracion;
    private javax.swing.JButton credito;
    private javax.swing.JComboBox departamentocombox;
    private javax.swing.JTextField departamentoe;
    private javax.swing.JTextField descripcion;
    private javax.swing.JButton factura;
    private javax.swing.JTextField ganancia;
    private javax.swing.JButton guardarDepartamento;
    private javax.swing.JButton inventario;
    private javax.swing.JComboBox ivacombox;
    private javax.swing.JTabbedPane ivas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mayoreo;
    private javax.swing.JTextField precioCompra;
    private javax.swing.JTextField precioVenta;
    private javax.swing.JButton productos;
    private javax.swing.JTextField smaximo;
    private javax.swing.JLabel smaximot;
    private javax.swing.JTextField sminimo;
    private javax.swing.JLabel sminimot;
    private javax.swing.JButton subir;
    private javax.swing.JButton subiriva;
    private javax.swing.JTable tablaDepartamento;
    private javax.swing.JTable tablaModificar;
    private javax.swing.JTable tablaiva;
    private javax.swing.JLabel tiva;
    private javax.swing.JTextField txtPorcentajeIva;
    private javax.swing.JRadioButton unidad;
    private javax.swing.JButton ventas;
    // End of variables declaration//GEN-END:variables
}
